baseURL = 'http://GANitak.io/'
languageCode = 'en-us'
title = 'GANitak.io'
favicon = "images/IMGanit.png"
theme= 'PaperMod'

[languages]
[languages.en]
description = "Space to think & write"
languageName ="English"
# Weight used for sorting.
weight = 1

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Journal'
  pageRef = '/Journal'
  weight = 20
[[menu.main]]
  name = 'Quotes'
  pageRef = '/quotes'
  weight = 30
[[menu.main]]
  name = 'Network'
  pageRef = '/Network'
  weight = 10
[[menu.main]]
  name = 'Security'
  pageRef = '/Security'
  weight = 10
[[menu.main]]
  name = 'Neat'
  pageRef = '/Neat'
  weight = 20
[[menu.main]]
  name = 'Sky'
  pageRef = '/Sky'
  weight = 30

[[menu.footer]]
  name = 'Terms'
  pageRef = '/terms'
  weight = 15
[[menu.footer]]
  name = 'Privacy'
  pageRef = '/privacy'
  weight = 10

[params]
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/GANitak/Loading/Moody"

#Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# defaultTheme: light
defaultTheme = "dark"
#defaultTheme: auto # to switch between dark or light according to browser theme
